name: Deploy to AKS

on:
  push:
    branches:
      - main
    paths:
      - "k8s/**"           # only trigger when K8s manifests change
      - ".github/workflows/deploy-to-aks.yml"
  workflow_dispatch:        # allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Get AKS Credentials
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      # (Optional) Set Docker image tag dynamically
      - name: Set image tag
        id: vars
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          echo "tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      # Update Kubernetes manifests with new image (optional if manifests use latest)
      - name: Update image in manifest
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APP_NAME }}:${{ steps.vars.outputs.tag }}|g" k8s/deployment.yaml

      # Deploy to AKS
      - name: Deploy manifests to AKS
        run: |
          kubectl apply -f k8s/

      # Verify rollout
      - name: Verify rollout status
        run: |
          kubectl rollout status deployment/${{ secrets.K8S_DEPLOYMENT_NAME }} --timeout=120s
